name: Terraform

on:
  push:
    branches:
    - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS Credentials
      env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
      run: |
        echo "AWS credentials configured"

    - name: Terraform Init
      run: terraform init

    - name: Check AWS credentials
      run: aws sts get-caller-identity

    - name: Terraform Plan
      run: terraform plan
