name: Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      run: |
        mkdir -p ~/.aws
        echo "[my_profile]" > ~/.aws/credentials
        echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        echo "region=us-east-1" >> ~/.aws/config
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS Credentials
      env:
        AWS_PROFILE: my_profile
      run: |
        echo "AWS profile set to my_profile"

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
