name: Terraform

on:
  push:
    branches:
    - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure SSH Keys
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ec2_key.pem
        chmod 600 ec2_key.pem
        echo "${{ secrets.EC2_PUBLIC_KEY }}" > ec2_key.pub

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var="ec2_public_key=${{ secrets.EC2_PUBLIC_KEY }}"
